// src/pages/login.vue
<template>
    <div className='login'>
        <div className='card'>
            <div className='left'>
                <h1>Hello World.</h1>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.Libero cum,
                    alias totam numquam ipsa exercitationem dignissimos,error nam,
                    consequatur.
                </p>
                <span>Don't you have an account?</span>
                <router-link to="/register">
                    <button>Register</button>
                </router-link>
            </div>
            <div className="right">
                <h1>Login</h1>
                <form>
                    <input type="text" :placeholder="inputPlaceholder" name='username' v-model="inputs.username" />
                    <input type="password" placeholder="Password" name='password' v-model="inputs.password" />
                    <a-button type="primary" :loading=isLoading @click.prevent="loginHandler">Login</a-button>
                    <p v-if="err" class="err">
                        {{ err }}
                    </p>
                </form>
            </div>
        </div>
    </div>
</template>

<script>
import { login } from '../query/queries';

export default {
    name: 'login',
    data() {
        return {
            inputs: {
                username: '',
                password: ''
            },
            err: "",
            isLoading: false
        }
    },
    computed: {
        inputPlaceholder() {
            return this.inputs.username ? this.inputs.username : 'Username';
        }
    },
    methods: {
        async loginHandler() {
            if (this.checkInputs() === "disqualification") return;

            this.isLoading = true;

            const res = await login(this.inputs);

            this.isLoading = false;

            // 未作登录失败逻辑
            this.$store.commit('curUserUpdate', res);
            this.$router.push("/");
        },
        checkInputs() {
            for (let key in this.inputs) {
                if (this.inputs[key] === "") {
                    this.err = "The form has blank space";
                    return "disqualification";
                }
            }
        },
    },
    mounted() {
        const username = this.$route.params.username;
        if (username) {
            this.inputs.username = username;
        }
    }
}
</script>

<style lang="scss">
.login {
    height: 100vh;
    background-color: rgb(193, 190, 255);
    display: flex;
    justify-content: center;
    align-items: center;

    .card {
        width: 50%;
        min-height: 600px;
        display: flex;
        background-color: #fff;
        border-radius: 10px;
        overflow: hidden;

        .left {
            display: flex;
            flex: 1;
            flex-direction: column;
            gap: 30px;
            background: linear-gradient(rgba(39, 11, 96, .5), rgba(39, 11, 96, .5)), url("https://i.328888.xyz/2023/03/20/PsE9H.jpeg") center;
            background-size: cover;
            padding: 50px;
            color: white;

            h1 {
                font-size: 100px;
                line-height: 100px;
            }

            span {
                font-size: 14px;
            }

            button {
                width: 50%;
                padding: 10px;
                border: none;
                border-color: #fff;
                color: rebeccapurple;
                font-weight: bold;
                cursor: pointer;
            }
        }

        .right {
            display: flex;
            justify-content: center;
            flex: 1;
            padding: 50px;
            flex-direction: column;
            gap: 50px;

            h1 {
                color: #555;
            }

            form {
                display: flex;
                flex-direction: column;
                gap: 30px;

                input {
                    border: none;
                    border-bottom: 1px solid lightgray;
                    padding: 20px 10px;
                }
            }

        }
    }
}
</style>

// src/pages/login/login.jsx
import { Link,
    useParams,
    useNavigate
} from "react-router-dom"
import { useState,useContext } from "react";
import { AuthContext } from "../../context/authContext";
import { Button } from "antd";
import './login.scss'

export default function Login() {
    const param = useParams();
    const [inputs, setInputs] = useState({
        username: param.username,
        password: ""
    });
    const [isLoading, setIsLoading] = useState(false);
    const [err, setErr] = useState("");
    const {login} = useContext(AuthContext);
    const navigate = useNavigate();

    function handleChange(e) {
        setInputs(prev => ({...prev, [e.target.name]: e.target.value}));
    }

    function checkInputs() {
        for(let key in inputs) {
            if(inputs[key] === "") {
                setErr("The form has blank space");
                return "disqualification";
            }
        }
    }

    async function handleLogin() {
        if(checkInputs() === "disqualification") return;
        setIsLoading(true);
        const res = await login(inputs);
        setIsLoading(false);
        if(res === 'success') {
            console.log('test');
            navigate("/");
        } else {
            setErr(res);
        }
    }

    return (
        <div className='login'>
            <div className='card'>
                <div className='left'>
                    <h1>Hello World.</h1>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.Libero cum,
                        alias totam numquam ipsa exercitationem dignissimos,error nam,
                        consequatur.
                    </p>
                    <span>Don't you have an account?</span>
                    <Link to='/register'>
                    <button>Register</button>
                    </Link>
                </div>
                <div className="right">
                    <h1>Login</h1>
                    <form>
                        <input type="text" placeholder={inputs.username ? inputs.username : 'Username'}
                            name='username' onChange={handleChange} />
                        <input type="password" placeholder="Password" name='password' onChange={handleChange} />
                        <Button type="primary" loading={isLoading} onClick={handleLogin}>Login</Button>
                        {err && err}
                    </form>
                </div>
            </div>
        </div>
    )
}
