// src/pages/register.vue
<template>
    <div class='register'>
        <div class='card'>
            <div class='left'>
                <h1>Hello World.</h1>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.Libero cum,
                    alias totam numquam ipsa exercitationem dignissimos,error nam,
                    consequatur.
                </p>
                <span>Do you have an account?</span>
                <router-link to='/login'>
                    <button>Login</button>
                </router-link>
            </div>
            <div class="right">
                <h1>Register</h1>
                <form>
                    <input type="text" placeholder='Username' name='username' v-model="inputs.username" />
                    <input type="email" placeholder='Email' name='email' v-model="inputs.email" />
                    <input type="password" placeholder="Password" name='password' v-model="inputs.password" />
                    <input type="text" placeholder='Name' name='nickname' v-model="inputs.nickname" />
                    <a-button type="primary" :loading="isLoading" @click="registerHandler">Register</a-button>
                    <p v-if="err" class="err">
                        {{ err }}
                    </p>
                </form>
            </div>
        </div>
    </div>
</template>

<script>
import { register } from '../query/queries';

export default {
    name: 'register',
    data() {
        return {
            inputs: {
                username: '',
                email: '',
                password: '',
                nickname: '',
            },
            isLoading: false,
            err: ''
        }
    },
    methods: {
        async registerHandler() {
            if (this.checkInputs() === "disqualification") return;
            this.isLoading = true;
            const res = await register(this.inputs);
            if (res === 'success') {
                this.isLoading = false;
                this.$router.push(`/login/${this.inputs.username}`);
            } else {
                this.err = res;
            }
        },
        checkInputs() {
            const inputs = this.inputs;
            for (let key in inputs) {
                if (inputs[key] === "") {
                    this.err = "The form has blank space";
                    return "disqualification";
                }
            }
            const reg = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
            if (!reg.test(inputs.email)) {
                this.err = "email format error";
                return "disqualification";
            }

            const len = inputs.password.length
            if (len < 6 || len > 20) {
                this.err = "The password length should be between 6 and 20";
                return "disqualification";
            }
        }
    }
}
</script>

<style lang="scss">
.register {
    height: 100vh;
    background-color: rgb(193, 190, 255);
    display: flex;
    justify-content: center;
    align-items: center;

    .card {
        display: flex;
        flex-direction: row-reverse;
        width: 50%;
        min-height: 600px;
        background-color: #fff;
        border-radius: 10px;
        overflow: hidden;

        .left {
            display: flex;
            flex: 1;
            flex-direction: column;
            gap: 30px;
            background: linear-gradient(rgba(39, 11, 96, .5), rgba(39, 11, 96, .5)), url("https://i.328888.xyz/2023/03/20/P9BtZ.jpeg") center;
            background-size: cover;
            padding: 50px;
            color: white;

            h1 {
                font-size: 100px;
                line-height: 100px;
            }

            span {
                font-size: 14px;
            }

            button {
                width: 50%;
                padding: 10px;
                border: none;
                border-color: #fff;
                color: rebeccapurple;
                font-weight: bold;
                cursor: pointer;
            }
        }

        .right {
            display: flex;
            justify-content: center;
            flex: 1;
            padding: 50px;
            flex-direction: column;
            gap: 50px;

            h1 {
                color: #555;
            }

            form {
                display: flex;
                flex-direction: column;
                gap: 30px;

                input {
                    border: none;
                    border-bottom: 1px solid lightgray;
                    padding: 20px 10px;
                }
            }
        }
    }
}
</style>

// src/pages/register/register.jsx
import { Link,useNavigate } from "react-router-dom"
import {register} from '../../query/queries';
import './register.scss'
import { useState } from "react";
import {Button} from 'antd'

export default function Register() {
    const [isLoading, setIsLoading] = useState(false);
    const [inputs, setInputs] = useState({
        username: "",
        email: "",
        password: "",
        nickname: ""
    })
    const [err, setErr] = useState("");
    const navigate = useNavigate();

    function handleChange(e) {
        setInputs(prev => ({...prev,[e.target.name]: e.target.value}));
    }

    function checkInputs() {
        for(let key in inputs) {
            if(inputs[key] === "") {
                setErr("The form has blank space");
                return "disqualification";
            }
        }
        const reg = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
        if(!reg.test(inputs.email)) {
            setErr("email format error")
            return "disqualification";
        }

        const len = inputs.password.length
        if(len < 6 || len > 20) {
            setErr("The password length should be between 6 and 20")
            return "disqualification";
        }
    }

    async function handleClick() {
        if(checkInputs() === "disqualification") return;
        setIsLoading(true); 
        const res = await register(inputs);
        if(res === 'success') {
            setIsLoading(false);
            navigate(`/login/${inputs.username}`);
            console.log('test');
        } else {
            setErr(res);
        }
    }

    return (
        <div className='register'>
            <div className='card'>
                <div className='left'>
                    <h1>Hello World.</h1>
                    <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.Libero cum,
                        alias totam numquam ipsa exercitationem dignissimos,error nam,
                        consequatur.
                    </p>
                    <span>Do you have an account?</span>
                    <Link to='/login'>
                        <button>Login</button>
                    </Link>
                </div>
                <div className="right">
                    <h1>Register</h1>
                    <form>
                        <input type="text" placeholder='Username' name='username' onChange={handleChange} />
                        <input type="email" placeholder='Email' name='email' onChange={handleChange} />
                        <input type="password" placeholder="Password" name='password' onChange={handleChange} />
                        <input type="text" placeholder='Name' name='nickname' onChange={handleChange} />
                        <Button type="primary" loading={isLoading} onClick={handleClick}>Register</Button>
                        {err && err}
                    </form>
                </div>
            </div>
        </div>
    )
}
