// client/src/components/posts/posts.jsx
import './posts.scss'
import Post from '../post/post';
import {useQuery} from '@tanstack/react-query';
import {makeRequest} from '../../axios';

export default function Posts({userId}) {
    const {isLoading, error, data} = useQuery(["posts"], () => {
        return makeRequest.get("/posts?userId=" + userId).then((res) => {
            console.log(res.data);
            return res.data;
        })
    })

    return (
        <div className="posts">
            {error ? 
            "Something went wrong!" :
            isLoading ? 
            "isLoading" :
            data.map(post => (
                <Post post={post} key={post.id}/>
            ))}
        </div>
    )
}

// src/components/posts.vue
<template>
    <div className="posts">
        <p v-if="error">
            {{ error }}
        </p>
        <loadingMark v-else-if="isLoading" />
        <Post v-else v-for="post in posts" :post="post" :key="post.id" />
    </div>
</template>

<script>
import { getAllPost, getPostByUserId } from '../request/post';

import Post from './post.vue';
import loadingMark from './loadingMark.vue'

export default {
    props: ["userId"],
    data() {
        return {
            isLoading: true,
            posts: [],
            error: "",
        }
    },
    components: {
        Post,
        loadingMark
    },
    mounted() {
        if (this.userId) {
            console.log("userId", this.userId);
            getPostByUserId(this.userId).then(res => {
                console.log(res);
                this.isLoading = false;
            }, reason => {
                this.error = reason;
            })
        } else {
            getAllPost().then(res => {
                console.log(res);
                this.posts = res.data.data
                this.isLoading = false;
            }, reason => {
                this.error = reason;
            })
        }
    }
}
</script>

<style lang="scss">
.posts {
    display: flex;
    flex-direction: column;
    gap: 50px;
}
</style>
